server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # URLs propres (Astro génère aussi /page.html)
  location / {
    try_files $uri $uri/ $uri.html /index.html;
  }

  # assets Astro : cache long
  location /_astro/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location = /robots.txt { access_log off; }
  location = /sitemap.xml { access_log off; }
}
